### ISSUE TITLE
[Feature request] option to hide statusline item if no notifications

### ISSUE THREAD

**Issue by akinsho** [rlch/github-notifications.nvim#2]
Hi @rlch, thanks for getting the `gh` cli working 👍🏿 , I've now swapped out my custom statusline component with this plugin's. One thing I had in my implementation was a way of hiding the statusline element if there were no notifications since I personally prefer having each item in my statusline only visible if there is content/something actionable e.g. a count of > 0 etc. I wonder if this could either be offered as an option, but that might be too specific 🤷🏿‍♂️ or alternatively maybe the count and icon could be returned in a table similar to gitsigns e.g. `{icon = "x", count = 1}` or a user could pass their own formatter function.

The first I think would be simplest, but not sure if this would be too specific a use case to accommodate 🤷🏿‍♂️

**Comment by rlch** [comment]
Thanks for this @akinsho, love the ideas! 😄 

I've added:
1. `statusline_notifications` export that returns a table as you suggested
2. A `hide_statusline_on_all_read` parameter in config (defaults to true)
3. Also included in this batch of commits is a mark all as read feature
