### ISSUE TITLE
 E5108: Error executing lua ...ns.nvim/lua/github-notifications/telescope/previewer.lua:23: attempt to concatenate field 'url' (a userdata value)

### ISSUE THREAD

**Issue by amaanq** [rlch/github-notifications.nvim#3]
As per the title, I get this error for **some** github notifications, not all..no idea why

E5108: Error executing lua ...ns.nvim/lua/github-notifications/telescope/previewer.lua:23: attempt to concatenate field 'url' (a userdata value)
stack traceback:
	...ns.nvim/lua/github-notifications/telescope/previewer.lua:23: in function 'define_preview'
	...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:386: in function 'preview'
	...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:1075: in function 'refresh_previewer'
	...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:1028: in function 'set_selection'
	...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:792: in function 'move_selection'
	.../packer/opt/telescope.nvim/lua/telescope/actions/set.lua:39: in function 'run_replace_or_original'
	...k/packer/opt/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'shift_selection'
	...packer/opt/telescope.nvim/lua/telescope/actions/init.lua:87: in function 'run_replace_or_original'
	...k/packer/opt/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...ack/packer/opt/telescope.nvim/lua/telescope/mappings.lua:341: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk

**Comment by rlch** [comment]
Hey @amaanq, pretty sure Github don't expose the URL for certain types of notifications. There's a better way of handling this than my "fix" in the `hooks` branch; which is just not to handle them lol - but currently don't have the time to implement a proper solution.

In the mean time, you should be able to use the `hooks` branch, but feel free to try implement a more rigorous solution to this.
